"""cria as tabelas iniciais

Revision ID: 93fcab46a778
Revises: 
Create Date: 2026-10-04 18:52:00.511154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93fcab46a778'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias',
    sa.Column('materia_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('materia_id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('usuario_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('nome_usuario', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('grupos',
    sa.Column('grupo_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('nome_grupo', sa.Text(), nullable=False),
    sa.Column('materia_id', sa.BigInteger(), nullable=False),
    sa.Column('max_participantes', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_participantes > 0', name='grupos_max_participantes_check'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.materia_id'], ),
    sa.PrimaryKeyConstraint('grupo_id')
    )
    op.create_index('idx_grupos_materia_id', 'grupos', ['materia_id'], unique=False)
    op.create_table('encontros',
    sa.Column('encontro_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('grupo_id', sa.BigInteger(), nullable=False),
    sa.Column('dia_semana', sa.SmallInteger(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('local', sa.Text(), nullable=False),
    sa.CheckConstraint('dia_semana between 1 and 7', name='encontros_dia_semana_check'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.grupo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('encontro_id')
    )
    op.create_index('idx_encontros_grupo_id', 'encontros', ['grupo_id'], unique=False)
    op.create_table('participacoes',
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('grupo_id', sa.BigInteger(), nullable=False),
    sa.Column('entrou_em', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.grupo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'grupo_id')
    )
    op.create_index('idx_participacoes_grupo_id', 'participacoes', ['grupo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_participacoes_grupo_id', table_name='participacoes')
    op.drop_table('participacoes')
    op.drop_index('idx_encontros_grupo_id', table_name='encontros')
    op.drop_table('encontros')
    op.drop_index('idx_grupos_materia_id', table_name='grupos')
    op.drop_table('grupos')
    op.drop_table('usuarios')
    op.drop_table('materias')
    # ### end Alembic commands ###
